In [3]:
import numpy as np

In [5]:
n=8

In [6]:
x=np.arange(n)

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
type(x)

numpy.ndarray

In [9]:
k=5

In [10]:
(k,n-k+1)

(5, 4)

In [11]:
x.itemsize

4

In [5]:
arr = np.array([1, 2, 3, 4], dtype = np.int64)
arr.itemsize

8

In [17]:
(x.itemsize,)

(4,)

In [20]:
(x.itemsize,)*2

(4, 4)

In [21]:
(2,2,2)*2

(2, 2, 2, 2, 2, 2)

In [22]:
(2,2)*2

(2, 2, 2, 2)

In [23]:
np.lib.stride_tricks.as_strided(x,(k,n-k+1) , (x.itemsize,)*2)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
(k,n-k+1)

(5, 4)

In [33]:
np.lib.stride_tricks.as_strided(x,(k+1,n-k+1) , (4,8))

array([[          0,           2,           4,           6],
       [          1,           3,           5,           7],
       [          2,           4,           6,           0],
       [          3,           5,           7,           0],
       [          4,           6,           0,  2067996744],
       [          5,           7,           0, -2147477248]])

In [35]:
new_arr=np.lib.stride_tricks.as_strided(x,(k,n-k+1) , (x.itemsize,)*2)
new_arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [36]:
new_arr[1,1]=-9

In [37]:
new_arr

array([[ 0,  1, -9,  3],
       [ 1, -9,  3,  4],
       [-9,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7]])

In [38]:
x

array([ 0,  1, -9,  3,  4,  5,  6,  7])